<a href="https://colab.research.google.com/github/aTunass/Cosine_similarity/blob/main/Zero_shot_text_classification_with_Bert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install transformers
!pip install torch


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 23.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 29.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 60.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.9 MB/s eta 0:00:00


# 2 Class

In [55]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [56]:
# Example text to classify
# text = "I really enjoyed the movie, it was fantastic!"
text = "I feel this dish is normal"

# Target classes that the model has not seen during training
target_classes = ["positive", "negative"]

# Tokenize the text and target classes
encoded_input = tokenizer(text, target_classes, return_tensors="pt", padding=True)

# Perform zero-shot text classification
with torch.no_grad():
    logits = model(**encoded_input).logits

# Get predicted class index
predicted_class_idx = torch.argmax(logits, dim=1).item()

# Get predicted class label
predicted_class = target_classes[predicted_class_idx]

print(f"Text: '{text}'")
print(f"Predicted Class: {predicted_class}")


Text: 'I feel this dish is normal'
Predicted Class: positive


In [57]:
print(logits)

tensor([[ 0.1871, -0.4093]])


In [58]:
print(torch.argmax(logits, dim=1).item())

0


# 3 Class

In [39]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification

# Định nghĩa các lớp nhãn mà chúng ta muốn phân loại
labels = ["dog", "cat", "human"]

# Load pretrained BERT model và tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=3)

# Chuỗi văn bản đầu vào bạn muốn phân loại
text = "A human playing with a dog"

# Tokenize văn bản và thêm token [CLS] và [SEP]
inputs = tokenizer(text, return_tensors="pt")

# Dự đoán xác suất cho các lớp nhãn
with torch.no_grad():
    outputs = model(**inputs)

# Lấy logits (scores) của các lớp nhãn
logits = outputs.logits

# Tính toán xác suất sử dụng hàm softmax
probs = torch.softmax(logits, dim=-1)

# Lấy lớp có xác suất cao nhất
predicted_label_idx = torch.argmax(probs, dim=1).item()
predicted_label = labels[predicted_label_idx]

print("Text:", text)
print("Predicted Class:", predicted_label)
print("Class Probabilities:", {label: prob.item() for label, prob in zip(labels, probs[0])})


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Text: A human playing with a dog
Predicted Class: cat
Class Probabilities: {'dog': 0.41399484872817993, 'cat': 0.4352542459964752, 'human': 0.15075090527534485}


In [42]:
print(logits)

tensor([[ 0.6992,  0.7492, -0.3111]])


In [40]:
print(probs)

tensor([[0.4140, 0.4353, 0.1508]])


In [41]:
print(predicted_label_idx)

1
